[package]
name = "phewmr-filter-snps"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
env_logger = "0.11.3"
flate2 = "1.0.30"
log = "0.4.21"
